global:
  message: Welcome to Online Movie Ticket Booking Platform
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exploruse:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/
spring:
  config:
    import: optional:configserver:http://localhost:8888
