global:
  message: Welcome to Booking Service - PROD!
server:
 port: 8093
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_prod
    username: root
    password: 
  jpa:
    hibernate:
     ddl-auto: update
     show-sql: true
    properties:
     hibernate:
     dialect: org.hibernate.dialect.MySQL8Dialect
     globally_quoted_identifiers: true
