global:
  message: Welcome to Booking Service!
server:
 port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_master
    username: root
    password: Password@254
  jpa:
    hibernate:
     ddl-auto: update
     show-sql: true
    properties:
     hibernate:
     dialect: org.hibernate.dialect.MySQL8Dialect
     globally_quoted_identifiers: true
