global: 
  messages: Welcome to Theatre Service - PROD Environment!
server:
  port:8084
spring:
  datasource:
    url: jdbc.mysql://localhost:3306/theatre_stage
    username: root
    password: Password@254
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
     dialect: org.hibernate.dialect.MySQL8Dialect
     globally_quoted_identifiers: true
